# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bf07a3bba1855242f9b59d75da693da"
name = "SmartDiscounts"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_customers,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
